# sizes
POPULATION_SIZE = 100
TOTAL_NUMBER_OF_ITERATIONS = 20
PARAMETERS_SIZE = 6
DATA_SEQUENCE_SIZE = 50
NDM_ROWS = 30  # 4 in tests
NDM_COLUMNS = 32  # 6 in tests
TOURNAMENT_CANDIDATES = 3
MAX_ITER_NO_PROG = 5  # should be lower than TOTAL_NUMBER_OF_ITERATIONS!!!

# rates
ACCEPTED_ERROR = 500.0
CROSSOVER_RATE = 0.8
MUTATION_RATE_DATA_SEQ = 0.2
MUTATION_RATE_PARAMS = 0.3
MUTATION_RATE_PARAMS_ZERO = 0.1

# Coefficients
M = 0.5
N = 0.5
