# sizes
POPULATION_SIZE = 100
TOTAL_NUMBER_OF_ITERATIONS = 7
PARAMETERS_SIZE = 6
DATA_SEQUENCE_SIZE = 50
NDM_ROWS = 20  # 4
NDM_COLUMNS = 22  # 6
TOURNAMENT_CANDIDATES = 3
MAX_ITER_NO_PROG = 3  # should be lower than TOTAL_NUMBER_OF_ITERATIONS!!!

# rates
ACCEPTED_ERROR = 500.0
CROSSOVER_RATE = 0.8
MUTATION_RATE = 0.2

# Coefficients
M = 0.5
N = 0.5
